import java.util.ArrayList;
import java.util.HashSet;

public interface View {
	void outputStart();  
	void outputFastCountRules();  
	void outputGreetings();;
	void outputEnterName(int n);; 
	void outputMorePlayers();  
	void outputEnterPlayersFastCount();  
	void outputEnterCounting();  
	void outputCountCheck(int n);  
	void outputCountCheckAgain(int n);  
	void outputEnterCountingAgain();  
	void outputEnterCountingFastCount();  
	void outputstartCounting(int n, int i);  
	void outputAllPlayers(ArrayList<String> arrayName, int w);  
	void outputConditions(ArrayList<String> arrayName, int wordsNumber);  
	void outputChooseGameMode();  
	void outputSetCountStartNumber();  
	void outputSetCountStepNumber();  
	void outputSetCountOrder();  
	void outputTempResult(ArrayList<String> arrayName, int num, String out);  
	void outputResult(ArrayList<String> arrayName);  
	void outputResultFastCount(ArrayList<Integer> arrayName);  
	void outputPlayAgain();  
	void outputChooseContinue(); 
	void outputAgainFromBegin();
	void outputAgainWithMyTeam();
	void outputFinal();  
	void outputIncorrectAnswer();  
	void outputIncorrectChoose();  
	void outputWhat();  
	void outputCheckedNumber();  
	void showFinalNumber(Calculate calculate);
	void showNumStep(Calculate calculate);
    void showOutPlayer(Calculate calculate);
    void showCountOrder(Calculate calculate);
	void showPlayersList(Players players);
	void showInitialPlayersList(Players players);
	void showFastCountPlayersList(Players players);
	void showSomeString(Words words);
	void showSomeNumber(Words words);
	void showWordsNumber(Words words);
	void showAnswer(Answers answer);
	void showConfirmationAnswer(Answers answer);
	void showPositiveAnswerList(Answers answer);
	void showNegativeAnswerList(Answers answer);
	void showString(String name, String value);
	void showNumber(String name, int value);
	void showBoolean(String name, boolean value);
	void showIntArrayList(String name, ArrayList<Integer> value);
	void showStringArrayList(String name, ArrayList<String> value);
	void showStringHashSet(String name, HashSet<String> value);
	void showIntHashSet(String name, HashSet<Integer> value);
}
	 
